language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

services:
   - mysql
env:
  - DJANGO=3.1.6
  - DB=mysql
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codecov
before_script:
  - mysql -e 'create database ecommerce_test;' -u root
script:
  - python manage.py test
after_sucess:
  - coveralls
  - codecov


  
