language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
services:
- mysql
env:
  matrix:
  - DJANGO=3.1.6
  - DB=mysql
  global:
  - DJANGO_SETTINGS_MODULE: 'ecommerce_backend.settings.travis'
  - secure: SCTi+UzXVkDc1/7xYx1tOuHAQ7ATgt1VRvkEPQNOHzH6jvzXCuYSukR1b4gNfz7ERvO7ZEo3+zlMpMKfU8UjLRrY92zBw6oO+hXG7yF5Cfz3aH1fWTx5T9zs2AptQCgMACINPlEmiuVHXwf686ZgC0cU1zvKyhsdLSvta+ikNXZGSgiMwpuw3rcgnIwGIA8T5KvnG3wV0z+rFoghP0fNRr5hicr85bbOzJkwbCuCcxBMXbDyA41ZtzmPMg8h5yQSA5aOffE9SoduaGpcaXpuTr9C74cVxxqrKfFGcDOa1UrXrz3SaL84VG2S7D82BpRc7XP+giQ2rFoKwo3uolK+c5H/NpSpLPnBaag0JSLe1SYO37UrD6rLJvNGImSVwI8umCnrbE6NBgTT8qVYd2EtHoj3QA6AqKhGg3AB7u7hJodyI/VYqqzTgpc/FnDYgb5hnWG2NprCDAJO5aicgU+5ylNJNJF/2B8ZdQNMncar3LjRp+KIc+2XiptV5cR6LImAeoT+ffg11+U5HXLa04SwPu5p6JFZ2oyTtMYqahr2hlCa0hF7DeMTzxJbceuey990Yb92lwu2l/PvbDlJfVF+5kQhAzyWvX1QZAwFNw0BUAmyXZ+tNFisgwfG54qyLXhMaaTk7nCLurk1glJdxO2L6G3Wk1QXQdr6Lfa4/BcjZmw=
  - secure: noUd1GxtbF/Fp2NAW/5r/LYh7D4W8t6RiddFLD8+PCh6zelD2pQ3HReXNZ0GvdMVhhxIQ1JjANjnuQr5LS+XTKjTcxF5+qX0TtsfCxhhC94ol5IHHecoZml0T+cLzC2mFwGVCGI9FXa9764egOg7pAT7+bSOf5fMHI/G5snRx3FL56oWol6OfCXcSHvkTVNvMY86nbCWnYA/mE517PwUrDOhaHFFvX5dxvv5eof3OJadkD/UidWY3S3jFuJkyJKUvFHs80/2PkMUnh0ZQQ3HNNsSupIkhZgwyuQR9x5pNvFFdjGWr7W2ZkcdbZsnvP1jXf22aSkEPjNcaSeWU82XuFswzrB/YnPaBj18SdE4bSd+2Cnybnn5TV9Dv7mXbRudXHSLc4rs2AnPTren+AOpc3xCvyHUezkxsjhvV5po40N94R3LJ8igrT1n8XuLou2ZBVaUcl61JPGs6WA5tIRSf0GLfqY7RBEGTskYFmfr2qt3hwnCHvhXw+S4yKXX7u+OegyxAOtyBPlHmZMlcaWn713ZX8lYTUWu3tHLrUPhHnzABpJrd3QwptCEFkWYZGs5p5G+NVV9V2OyIhRibeZ6UaJPfjeknBszu/fX1ZenzaPlkDDx4E2+mC7z7dKIhnOpVjO+n5sxxtluDA51EA5vov+Zy3r85XiyA0PYWafQRH0=
  - secure: qIh4V5ZED1jkRV01Uv34cNE0i+Ma695YjHe1tULg2ZpzVpErgrsUJAe+SvhXxtxmqZaw4pH9VO3yr5tJS0J7Z9idj9YC8dmiysfgnoj8zIu6KXqtoMCfQjhCpKc1ct2wFfxCw+GYZj8vo9gq8e7v+j3HGyCsTiqXje89bRzGr7Ehw3exZ7M2Q5dzKi2lLLqKGkS4X4KNC/cGBkxbP8Oy57IcC1tW/wvc6e+hpegB7ykZFIXGIh6UYhDevzCeOViclD6tU/fHEMxWdKib/n+feTFyOy6pf1dcAOBB5kex3pXxqG+YjW+0FOjORyFFHOPyCMyxOHsgsuYKKj8bScY5ACnE5Wkjq+dgzp+FLir8Qh4lLMnPkXHcVDWP49nADBbyEjc3KbAFF24scBqnrh8xHrU3+5GqIlGmdY1/HBxkGIKGr2NFFY0D+hfSbji4EUj+wNh4DxpKwR/dwzuI2yS/Cs7TBQdzVLZJp9FKA7CKSCZblsW5HjiHZLgwSiRuL9f1fgUvFxlBdx5WAayjl0fjUDJ6mi01sM6uuoATx4EaGRwW1D3ZsoZzzADT1gHq8MQ6HPKRzoGeNWb3SXAN7CYld8nhaR7+BZVTDJ6L8Twtnbk6sPcpbOZNGZiQXg4M30NJqbvyB763JKpcp0U9NJDOQad+dYQMxM4+puX304oY5g8=
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage
- pip install codecov
before_script:
- mysql -e 'create database ecommerce_test;' -u root
script:
# - python manage.py test
- pytest --cov=products --cov-report=term-missing

after_sucess:
- coveralls
- codecov
